package com.ncst.selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AATest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver",
            "D:\\java\\driver\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aA() {
    driver.get("https://dev.info2soft.com/index.php?m=my&f=index&tid=2d86timq");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.switchTo().frame(0);
    driver.findElement(By.linkText("文档")).click();
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".radio-inline:nth-child(4)")).click();
    driver.findElement(By.id("submit")).click();
    driver.switchTo().defaultContent();
    driver.switchTo().defaultContent();
    driver.switchTo().frame(1);

    driver.findElement(By.linkText("员工日周报")).click();

    driver.findElement(By.linkText("/")).click();
    driver.findElement(By.linkText("日报-李石岩-2023/1/17")).click();
    driver.findElement(By.cssSelector(".active-result:nth-child(57)")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("33eee");
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".article-content")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector("#mailto_chosen > .chosen-choices")).click();
    driver.findElement(By.cssSelector("#mailto_chosen .default")).sendKeys("erere");
  }
}
