package com.ncst.selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class ABTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver",
            "D:\\java\\driver\\chromedriver_win32\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void aB() throws InterruptedException {

    //打开百度网站
    driver.get("https://dev.info2soft.com/index.php?m=my&f=index");
    //TimeUnit.SECONDS.sleep(5);

    driver.findElement(By.id("account")).sendKeys("lisy1");
    driver.findElement(By.xpath("//*[@id=\"loginPanel\"]/div/div[2]/form/table/tbody/tr[2]/td/input")).sendKeys("Lsy@1997,.?");
    driver.findElement(By.xpath("//*[@id=\"submit\"]")).click();

    driver.get("https://dev.info2soft.com/index.php?m=my&f=index&tid=2mys0pmg");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".icon-plus-solid-circle")).click();
    driver.findElement(By.linkText("文档")).click();
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".radio-inline:nth-child(4)")).click();
    driver.findElement(By.id("submit")).click();
    TimeUnit.SECONDS.sleep(1);
    driver.switchTo().defaultContent();
    driver.switchTo().frame(1);
    driver.findElement(By.linkText("员工日周报")).click();
    driver.findElement(By.cssSelector(".active-result:nth-child(10)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#module_chosen > .chosen-single > div:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("#module_chosen .chosen-search"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.linkText("/")).click();
    driver.findElement(By.cssSelector(".active-result:nth-child(57)")).click();
    driver.findElement(By.id("title")).click();
    driver.findElement(By.id("title")).sendKeys("CC");
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".article-content")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector("#mailto_chosen > .chosen-choices")).click();
    driver.findElement(By.cssSelector("#mailto_chosen .default")).sendKeys("CC");
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".article-content")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector("#mailto_chosen > .chosen-choices")).click();
    driver.findElement(By.cssSelector("#mailto_chosen .default")).sendKeys("s");
    driver.findElement(By.cssSelector("#mailto_chosen .search-field")).click();
    driver.findElement(By.cssSelector("#mailto_chosen li:nth-child(5)")).click();
  }
}
